plugins {
    id 'dev.architectury.loom' version '1.10.437'
    id 'maven-publish'
}

version = "${project.mod_version}"
group = "${project.mod_group_id}"

base {
    archivesName = "${project.mod_name}-mc${project.minecraft_version}"
}

loom {
    forge {
        mixinConfig "fastload.mixins.json"
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

repositories {
    mavenCentral()
    maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://maven.parchmentmc.org' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.20.1:2023.09.03@zip")
    }
    forge "net.minecraftforge:forge:${project.loader_version}"

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, 
            minecraft_version_range: "[1.20.1,1.21)",
            forge_version: forge_version, 
            forge_version_range: "[47,)",
            loader_version_range: "[47,)",
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            credits: credits, mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
